### ISSUE TITLE
cant start localstack

### ISSUE THREAD

**Issue by fridtjofaugust** [jimsheldon/terraform-aws-network-example#33]
Hi, Im sorry but it seems I cant start localstart running:
docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:1.2.0

![image](https://user-images.githubusercontent.com/109080051/205316502-2510cb4e-2c32-4c87-9487-b619b6682346.png)

Can you help me?

**Comment by jimsheldon** [comment]
Looks like Docker is not running on your machine.

Sorry for the late reply! I will close this.
